issuer: https://token.actions.githubusercontent.com
subject: repo:chps-dev/chps-scorer:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chps-dev/chps-scorer/.github/workflows/digestabot.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
